In [30]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from utils import *

In [2]:
iris = datasets.load_iris()
X = pd.DataFrame(iris.data, columns = iris.feature_names)
y = iris['target']

In [3]:
scaler = StandardScaler()
scaler.fit(X)
X_scaled = pd.DataFrame(scaler.transform(X), index= X.index, columns= X.columns)
X_scaled.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [8]:
data_list = Data_list(X_scaled)
results = Parrallel_compute(data_list, typeComplex='Alpha')

X_scaled['topo_feature'] = [x.tolist()[0][0] if isinstance(x, np.ndarray) else x for x in results]
X_scaled['topo_feature'] = scaler.fit_transform(X_scaled[['topo_feature']])
X_scaled.head()

平行運算時間:  0.17385601997375488


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0          -0.900681          1.019004          -1.340227         -1.315444   
1          -1.143017         -0.131979          -1.340227         -1.315444   
2          -1.385353          0.328414          -1.397064         -1.315444   
3          -1.506521          0.098217          -1.283389         -1.315444   
4          -1.021849          1.249201          -1.340227         -1.315444   

   topo_feature  
0      0.169697  
1      0.167484  
2      0.157600  
3      0.163232  
4      0.160600

In [21]:
X_final = X_scaled.iloc[:, :4]#.to_numpy()
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y, test_size=0.5, random_state=42)

X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_train = pd.Series(y_train).reset_index(drop=True)
y_test = pd.Series(y_test).reset_index(drop=True)

## Origin

In [23]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
dtree.score(X_test, y_test)

0.9466666666666667

In [24]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

training_prediction = log_reg.predict(X_train)
test_prediction = log_reg.predict(X_test)

print("Precision, Recall, Confusion matrix, in training\n")
print(metrics.confusion_matrix(y_train, training_prediction))
print(metrics.accuracy_score(y_train, training_prediction))

Precision, Recall, Confusion matrix, in training

[[21  0  0]
 [ 0 24  3]
 [ 0  2 25]]
0.9333333333333333


### Adding Topology feature

In [25]:
X_final = X_scaled
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y, test_size=0.5, random_state=42)

X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_train = pd.Series(y_train).reset_index(drop=True)
y_test = pd.Series(y_test).reset_index(drop=True)

In [28]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
dtree.score(X_test, y_test)

0.8933333333333333

In [29]:
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

training_prediction = log_reg.predict(X_train)
test_prediction = log_reg.predict(X_test)

print("Precision, Recall, Confusion matrix, in training\n")
print(metrics.confusion_matrix(y_train, training_prediction))
print(metrics.accuracy_score(y_train, training_prediction))

Precision, Recall, Confusion matrix, in training

[[21  0  0]
 [ 0 24  3]
 [ 0  2 25]]
0.9333333333333333
